##############################################
# Credenciais do Supabase
##############################################
[db]
host = "aws-1-sa-east-1.pooler.supabase.com"
port = 6543
database = "postgres"
user = "postgres.speqvhezemoacfcxtbpf"
password = "ZD_H9RpLRN.+f&S"
sslmode = "require"
