##############################################
# Credenciais do Supabase
##############################################
[db]
host = "aws-0-us-west-2.pooler.supabase.com"
port = 6543
database = "postgres"
user = "postgres.qnvvxedgnwplhwapceyb"
password = "kRNH4MJa9AI806wT"
sslmode = "require"